### ISSUE TITLE
Route::get('{path}',"HomeController@index")->where( 'path', '([A-z\d-\/_.]+)?' ); not working

### ISSUE THREAD

**Issue by rajiphilip** [Hujjat/laravStart#11]
Route::get('{path}',"HomeController@index")->where( 'path', '([A-z\d-\/_.]+)?' ); not working when i refresh the page. i am using PHP 7.3.1

**Comment by Hujjat** [comment]
Can you show me your web.php code here ??

**Comment by yassineDevox** [comment]
hello my super prof 🥇  
when i try to access by just taping url like http://localhost:8000/drivers i go the same error

**Comment by Hujjat** [comment]
Hi buddy, 
Can you please show me your error please.  ?

**Comment by agusrupendi** [comment]
this is the error...

ErrorException (E_WARNING)
preg_match(): Compilation failed: invalid range in character class at offset 20

**Comment by Rohiri** [comment]
Try this Route::get('{path}','HomeController@index')->where( 'path', '([A-z\d\-/_.]+)?' );

**Comment by Samk13** [comment]
This will solve the problem with laravel ^6.2 :

`
Route::get('/{any}', 'HomeController@index')->where('any', '.*');
`

**Comment by khaled2315** [comment]
This will solve the problem with laravel ^7.*:

Route::get('/{any}', 'HomeController@index')->where('any', '.*');
