### ISSUE TITLE
"preg_match(): Compilation failed: invalid range in character class at offset 20"

### ISSUE THREAD

**Issue by nani102** [Hujjat/laravStart#13]
C:\wamp64\www\Laravel\laravelvue\vendor\laravel\framework\src\Illuminate\Routing\Matching\UriValidator.php
 
namespace Illuminate\Routing\Matching;
 
use Illuminate\Http\Request;
use Illuminate\Routing\Route;
 
class UriValidator implements ValidatorInterface
{
    /**
     * Validate a given rule against a route and request.
     *
     * @param  \Illuminate\Routing\Route  $route
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    public function matches(Route $route, Request $request)
    {
        $path = $request->path() === '/' ? '/' : '/'.$request->path();
 
        return preg_match($route->getCompiled()->getRegex(), rawurldecode($path));
    }
}
 
Arguments
"preg_match(): Compilation failed: invalid range in character class at offset 20"

web.php file..
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('{path}',"HomeController@index")->where( 'path', '([A-z\d-\/_.]+)?' );

**Comment by iqbalmalik89** [comment]
how it is solved?
