### ISSUE TITLE
image 404

### ISSUE THREAD

**Issue by PhyoKyawKyaw** [Hujjat/laravStart#14]
i got localhost/:1 GET http://localhost:8000/img/profile/ 404 (Not Found) in image

**Comment by bedo89** [comment]
i have same problem as well

**Comment by ShekhSaifuddin007** [comment]
npm install not working it's showing me lot of error... :(

**Comment by Hujjat** [comment]
Hey @ShekhSaifuddin007 
May I know what's the error you get while runing ` npm install ` ??
