### ISSUE TITLE
Add new user, error 500

### ISSUE THREAD

**Issue by fauziardiyanto** [Hujjat/laravStart#17]
Hello there, I already installed the laravstart, with following your last video on your playlist, unfortunately, when I try to add a new user, it's always stuck with error 500 internal server error, why is this thing happen?

**Comment by amroberto** [comment]
Theo same thing happing with me.
The tabble off users don`t show users And the Button of form os inactived withoud ActionScript in muito case.
Tks

**Comment by fauziardiyanto** [comment]
If the table user didn't show up, you need to install laravel passport first bro.

**Comment by Hujjat** [comment]
Did you guys installed Laravel Passport ??

**Comment by fauziardiyanto** [comment]
I was following your last video on the playlist, and yes, I already installed laravel passport

**Comment by fauziardiyanto** [comment]
hi there, @Hujjat , I think I found the problem, while I rewatching your youtube playlist, the database on the photo, it's not nullable, so when I change it on mysql to be nullable, I can save a user.

**Comment by Hujjat** [comment]
Hi @fauziardiyanto 
Nice find. Thank you so much for that. :)
