### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by codeslack** [Hujjat/laravStart#18]
1. Error after deploy my vps server when reload or press F5 key

"preg_match(): Compilation failed: invalid range in character class at offset 20"
but "https://api.u2pay.in/home" no error 

Route::get('{path}',"HomeController@index")->where( 'path', '([A-z\d-\/_.]+)?' );

2. You are running Vue in development mode.
Make sure to turn on production mode when deploying for production. how to solve.

**Comment by Hujjat** [comment]
Hi there, Please update your web.php file with 
` Route::get('{path}',"HomeController@index")->where( 'path', '/([A-z\d-\/_.]+)?/' ); `

2. Run ` npm run prod ` to compile your assets for production. 

Thanks.

**Comment by codeslack** [comment]
but not work

**Comment by Hujjat** [comment]
Hi, 

Can you please try this `Route::get('{path}',"HomeController@index")->where( 'path', '([A-z\d-\/_.]+)?' );`

If doesn't work, it's probably related to PHP version you're using. I have seen similar issue with PHP7.3
