### ISSUE TITLE
Error during npm install

### ISSUE THREAD

**Issue by maxi032** [Hujjat/laravStart#20]
Hi
During npm install I got
ENOENT: no such file or directory, open '/home/vagrant/code/multipurpose/node_modules/acorn-dynamic-import/node_modules/acorn/package.json.3815591402'
Any ideeas why?

I am using homestead with npm v6.9.2 and node v12.5

**Comment by maxi032** [comment]
Problem solved by deleting node_modules and using yarn install instead of npm install

**Comment by Hujjat** [comment]
Hi @maxi032 

Thanks for confirming :)
