### ISSUE TITLE
I am getting error create form is not submitted

### ISSUE THREAD

**Issue by blpraveen** [Hujjat/laravStart#5]
The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR)GET - http://localhost:8000/api/user

**Comment by Hujjat** [comment]
can you please give an screenshot of your errors ?

**Comment by ilderjco** [comment]
![image](https://user-images.githubusercontent.com/11062147/71538248-ddb5d000-28f5-11ea-98f8-f0e1938dc8bb.png)
Help me please
