### ISSUE TITLE
 npm ERR! A complete log of this run can be found in:

### ISSUE THREAD

**Issue by IsoftTech** [Hujjat/laravStart#8]
I was following your videos from youtube, but on getting to where i was suppose to vform i got this error, then i tried some help online but it still didn't work. now if i tried runing anything with npm it not working again. please help me
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Isoft\AppData\Roaming\npm-cache\_logs\2018-12-28T00_39_00_413Z-debug.log

**Comment by Hujjat** [comment]
Hi buddy. 

As the error says, it's a npm issue. Please read the following issues for fixs. 

https://github.com/npm/npm/issues/19353
https://github.com/npm/npm/issues/19672

**Comment by IsoftTech** [comment]
It still didn't work for me here are the error: 
available in ES6 (use 'esversion: 6'). (W119),
Missing semicolon. (W033)
Missing semicolon. (W033)
'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz). (W104)
Missing semicolon. (W033)
'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz). (W104)
'object short notation' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz). (W104)
Missing semicolon. (W033)
'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz). (W104)
'object short notation' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz). (W104)
For this,  i can't install any packages
installing vform i got this error
npm i axios vform
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Isoft\AppData\Roaming\npm-cache\_logs\2018-12-28T11_37_30_721Z-debug.log
