### ISSUE TITLE
DevTools failed to parse SourceMap error after login will redirect to that js file

### ISSUE THREAD

**Issue by shiroamada** [Hujjat/laravStart#9]
Hi,

Can you help in this issue?

https://stackoverflow.com/questions/54041556/devtools-failed-to-parse-sourcemap-error-after-login-will-redirect-to-that-js-fi

**Comment by Hujjat** [comment]
Hi buddy, 
This error happens when you have an error and compile your javascript code. Later, when you fix it, it will remain in cache and happens. Please try to compile your script again and login to see

**Comment by shiroamada** [comment]
ok, after I run `npm update`, and run `npm run watch`, it seem like no issue any more. Thanks!
